### ISSUE TITLE
Break your code down

### ISSUE THREAD

**Issue by felixfong227** [ponydevs/MLPVC-BOT#2]
I think if you break your code base down, it will make your life much more easier, like turn your `commandsArray` to a JSON file instead

**Comment by SeinopSys** [comment]
Thank you for your feedback. I've tried breaking the codebase up in the past, but there are way too many cross references to make it feasible. The permissions used in the objects within the array cannot be accessed from other JS files. Making an object to store the permissions and only storing the keys could be an option, but I can't help feeling that it'd just be complicating things for the sake of making things more complicated. I can collapse the object in my IDE so I don't really mind it being there either.

**Comment by felixfong227** [comment]
But it is not a good thing to stick a bunch of code together, maybe you can create some unit test, and try breaking code down?

**Comment by SeinopSys** [comment]
If I had infinite free time and it'd be required for the code to work then I would consider trying again. As of now my attempts at simplification failed miserably so I'm just going to leave everything in one file as it seems to work perfectly fine for my purposes.

**Comment by SeinopSys** [comment]
Fixed in 730db734bb1c31493c4b0e02d9ecf5d12f6eb757
